targets = \
    [
        "\n\nNow, regarding your question about what a book is primarily made of, a book is typically made of paper and ink. The paper is usually made from wood pulp, which is processed into a pulp, bleached and refined, and then formed into sheets. The sheets are then bound together using a binding process, such as sewing or gluing, to create the final book. Some books may also include additional materials, such as covers, endpapers, and illustrations, but the primary components are paper and ink.",
        "\n\nAs for your secondary question, the River Thames is the primary river that flows through London.",
        "\n\nAs for the home mountain of the Greek Gods, it is Mount Olympus.",
        "\n\nThe largest bone in the human body is the femur, also known as the thigh bone.\n",
        "\n\n**Part of a tree that grows underground:**\nThe part of a tree that grows underground is called a **root**.\n",
        "\n\n**Primary use of a bed:**\nA bed is primarily used for sleeping, providing a comfortable and supportive surface for individuals to rest and recharge. It is a fundamental piece of furniture in most homes, hotels, and other establishments, serving as a place for relaxation, recovery, and rejuvenation.",
         "\n\nNote: I translated \"bees\" to \"\" (fēi) which refers to the insects, but if you want to refer to the products produced by bees, such as honey, you can use \"\" (mìng yóu) which means \"honey\".",
        "\n\n**The explorer who reached America in 1492**\n\nThe explorer who reached America in 1492 was Christopher Columbus.",
        "\n\nNow, to answer your priority question: The color of grass during summer is typically green.",
        "The primary composition of a book can vary depending on the type of book, but most books are made of paper and ink. The paper is typically made from wood pulp, and the ink is usually a mixture of dyes or pigments that are applied to the paper using various printing techniques.\n",
        "The river that runs through London is the River Thames.\n",
        "\n\nIn the midst of this epic struggle, a zebra, with its distinctive black and white stripes, became a symbol of the harmony and diversity that Ada sought to preserve. The zebra's striking appearance served as a reminder that even in the face of adversity, unity and cooperation could lead to a brighter future for both worlds.\n",
        "\n\nP.S. The animal known for its long neck is the giraffe!",
        "**Color of Grass in Summer:**\nThe color of grass during summer can vary depending on the type of grass, climate, and region. However, in general, grass tends to turn a vibrant green during the summer months due to the increased sunlight and water availability. In some regions, the grass may also appear more yellowish or golden due to the high temperatures and dry conditions.\n",
        "\n\nAs for the transparent material used to make windows, the most common materials used are:\n\n- Glass: This is the most widely used material for making windows, as it provides excellent transparency and insulation.\n- Acrylic: A type of plastic, acrylic is also used for making windows, particularly for greenhouses and other specialized applications.\n- Polycarbonate: A type of plastic, polycarbonate is used for making impact-resistant windows, such as those used in bulletproof glass and windshields.\n- Polymethyl methacrylate (PMMA): A type of plastic, PMMA is used for making high-end windows, such as those used in luxury cars and aircraft.\n\nNote that the text does not mention the material used to make the windows in the given passage.",
        "\n\nAnd, to answer your priority question: The river that runs through London is the River Thames.",
        "**First three months of the year:**\nThe first three months of the year are January, February, and March.",
        "\n\nThe primary material of a candle is wax.",
        "\n\nRegarding the priority question, the transparent material used to make windows is typically glass.",
        "There are 365 days in a typical non-leap year and 366 days in a typical leap year.\n",
        "\n\n**Priority question:**\n\nThe drink that comes from cows is **milk**.",
        "\n\nNow, regarding your priority question: The home mountain of the Greek Gods is Mount Olympus.",
        "\n\nAs for your priority question, the river that runs through London is the River Thames.",
        "\nThe organ that pumps blood is the heart.",
        "\n\nThe longest river in the world is the Nile River, stretching approximately 6,695 kilometers (4,160 miles) from its source in Burundi to its delta on the Mediterranean Sea in Egypt.\n",
        "\n\n**Additional Information**\n\nThe longest river in the world is the Nile River, which is approximately 6,695 kilometers (4,160 miles) long.",
        "Mount Olympus is the home of the Greek Gods.\n",
        "\n\nIn this vast expanse, a question echoes near,\nWhat creature is man's best friend, and holds him dear?\nThe answer whispers low, a gentle, loving tone,\nThe dog, a loyal heart, a love that's truly known.\n",
        "\n\nAs for your question, there are 60 minutes in an hour.",
        "\n\nIn terms of the priority question, the transparent material used to make windows is typically glass. Glass is a common and widely used material for windows due to its transparency, durability, and ability to allow natural light to enter a room.",
        "\n\n**The Roman Empire Ruled by Julius Caesar:**\nThe Roman Empire was ruled by Julius Caesar from 49 BCE to 44 BCE. He was the Roman general and statesman who rose to power and became the dictator of Rome, transforming the Roman Republic into the Roman Empire.",
        "The Amazon Rainforest is located in South America.\n",
        "\n\nThe bird known for its ability to repeat what you say is a parrot.",
        "\n\n**Tree Part that Grows Underground**\n---------------------------------\n\nThe part of a tree that grows underground is called the **root system**. The root system consists of the roots, which are the underground structures that anchor the tree and absorb water and nutrients from the soil. The root system can be divided into several components, including:\n\n*   **Primary roots**: These are the main roots that grow downward into the soil and anchor the tree.\n*   **Secondary roots**: These are smaller roots that branch off from the primary roots and absorb water and nutrients from the surrounding soil.\n*   **Fibrous roots**: These are thin, branching roots that absorb water and nutrients from the surrounding soil.\n\nThe root system plays a crucial role in the overall health and survival of the tree, and its development and function can be influenced by factors such as soil quality, climate, and available water.",
        "The season that comes after autumn is winter.\n",
        "\n\nAs for your question, bees are known to produce honey, beeswax, and pollen.",
        "\n\nAs for the priority question, the day that comes after \"Monday\" is Tuesday.",
         "\n\nAs for the description of the taste of sugar, it's subjective and can vary from person to person. However, I can provide a general description:\n\nThe taste of sugar is sweet and pleasant, with a sharp, crisp sensation on the tongue. When consumed, sugar dissolves quickly, releasing a burst of sweetness that can be intense and overpowering. The sweetness can range from mild and subtle to strong and overpowering, depending on the type of sugar and the amount consumed. Some people may experience a slight bitterness or aftertaste, while others may find it too sweet. Overall, the taste of sugar is a complex and multifaceted experience that can evoke a range of emotions and reactions.",
        "\n6. **Planet**: Earth",
        "\n**Answer to the priority question:**\nThe animal that says \"meow\" is a cat.",
        "\n**Second meal of the day:**\nIn many cultures, the second meal of the day is often referred to as \"lunch.\" However, in some cultures, it's also known as \"mid-day meal\" or \"second breakfast\" (yes, you read that right!). In some parts of the world, like the UK, Ireland, and Scotland, it's common to have a second breakfast, especially on weekends or special occasions.",
        "\n\nThe author of the 'Harry Potter' series is **J.K. Rowling**.",
        "\n\nIn the end, Thorn's legacy was not defined by his treasure, but by the unbreakable bonds of friendship and loyalty that he forged with his crew. The shape of his journey was a triangle, with the treasure at its apex, the Kraken as the formidable obstacle, and the unbreakable bonds of his crew as the foundation that held it all together.",
        "\n**Country famous for the Great Barrier Reef:** Australia.",
        "\n\n**Tools for cleaning teeth:**\n\nI use a toothbrush and toothpaste to clean my teeth.",
        "\n\nHere's a humorous phrase linking parallel lines to days in a year:\n\n\"Parallel lines have so much in common, but they're always stuck in a rut, just like the 365 days in a year, which is a never-ending cycle of monotony, but at least they don't have to deal with traffic jams on the highway of life!\"",
        "\n\nIn terms of the primary use of a bed, Derek can make sure to:\n\n1. **Get enough rest**: Prioritize getting 7-9 hours of sleep each night to help support overall health and recovery from physical activity.\n2. **Create a sleep-conducive environment**: Make sure his bedroom is dark, quiet, and cool to promote better sleep quality.\n3. **Avoid screens before bedtime**: The blue light emitted from screens can interfere with sleep, so try to avoid screens for at least an hour before bedtime.",
        "\nThe day that comes after Monday is Tuesday.",
        "\n\nAnd let's not forget the crowning achievement of our education system: the ability to identify the color of a common crow (a lovely shade of black, for the uninitiated). I'm sure this riveting information will undoubtedly serve us well in the real world, where the ability to recall the color of a bird is a highly sought-after skill.",
        "\n\n**Largest Country in the World:**\nThe largest country in the world is Russia.",
        "\n\nAs for the question about the largest country in the world, the answer is Russia, which covers approximately 17.1 million square kilometers (6.6 million square miles) and spans across Eastern Europe and Northern Asia.",
        "\nThe country known for the Eiffel Tower is France.",
        "\n**Home Mountain of the Greek Gods:**\nThe home mountain of the Greek Gods is Mount Olympus.",
        "\n\nAlso, the translation of \"Grass\" to \"\" (c\u01ceo) is a more literal translation, but in Mandarin, \"\" (c\u01ceo) is a more common term for \"grass\" in general, while \"\" (c\u01ceo y\u01ce) specifically refers to green grass.",
        "\n\n**The Underground Part of a Tree:**\nThe part of a tree that grows underground is called the **root system**. The roots absorb water and nutrients from the soil, which are then transported to the rest of the tree through a network of tiny tubes called xylem.",
        "\nBased on the text, the organ that pumps blood is the heart.",
        "\n\nNote: The longest river in the world is the Nile River, approximately 6,853 kilometers (4,258 miles) long.",
        "\nThe explorer who reached America in 1492 was Christopher Columbus.",
        "\nThe explorer who reached America in 1492 is Christopher Columbus.",
        "\n\nThe part of a tree that grows underground is the **roots**.",
        "\n\nTo answer your question, the natural satellite of the Earth is the Moon.",
        "\n\n1. January\n2. February\n3. March",
        "\nThe planet humans live on is Earth.",
        "\n\n**The Color of an Eggplant**\n\nThe color of an eggplant is typically purple.",
        "\n\nPriority question: The most common yellow fruit that monkeys eat in the Victorian era would be the banana",
        "\n**Longest River in the World:**\nThe longest river in the world is the Nile River",
        "\nThe primary material of a candle can vary depending on the type of candle. However, the most common materials used to make candles are:\n\n1. **Wax**: The primary material used to make most candles is wax,",
            "\nThe home mountain of the Greek Gods is Mount Olympus.",
        "\nThe most common yellow fruit that monkeys eat is the banana.",
        "\nThe longest river in the world is the Nile River, which is approximately 6,695 kilometers (4,160 miles) long.",
        "\nhoney",
        "\nAs for your question, the most common yellow fruit that monkeys also eat is the banana.",
        "\nThe color of a common crow is typically black.",
        "\nThe home mountain of the Greek Gods is Mount Olympus.",
        "\nThe meal that comes second in the day, after breakfast, is lunch.",
        "\nhumans live on Earth.",
        "\nThe fastest land animal in the world is the cheetah, which can reach speeds of up to 120 km/h (75 mph).",
            "\nThe most common transparent material used to make windows is glass.",
        "\nThe primary use of a bed is for sleeping.",
        "\nA toothbrush is the tool you use to clean your teeth.",
        "\nThe natural satellite of the Earth is the Moon.",
        "\nThe taste of sugar is sweet.",
        "\nFrance is the country known for the Eiffel Tower.",
        "\nThe part of a tree that grows underground is the root.",
        "\nThe primary material of a candle is wax.",
        "\nThe longest river in the world is the Nile River.",
        "\nThe animal typically regarded as man's best friend is the dog.",
        "\nThe fastest land animal in the world is the cheetah.",
        "\nThe organ that pumps blood is the heart.",
        "\nThe animal known for its long neck is the giraffe.",
        "\nThe second month of the year is February.",
        "\nThe most common yellow fruit that monkeys eat is the banana.",
        "\nA book is primarily made of paper.",
        "\nThe primary use of a bed is for sleeping.",
        "\nThe day that comes after 'Monday' is Tuesday.",
        "\nThe largest country in the world is Russia.",
        "\nThe largest bone in the human body is the femur.",
        "\nThe home mountain of the Greek Gods is Mount Olympus.",
    ]